version: "3.9"

services:
  db:
    image: postgres:16
    container_name: workout_db
    restart: always
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data